spring:
  datasource:
      url: jdbc:mysql://host:port/name?characterEncoding=utf8&useSSL=false
      username: root
      password: xiaoji1019A$
      hikari:
        connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
